# Generated by Django 5.0.1 on 2025-09-11 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.organization'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='teams.role'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='teams_organ_slug_fee948_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name',), name='org_name_unique_global'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['org', 'name'], name='teams_role_org_id_89d701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('org', 'name')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['org', 'name'], name='teams_team_org_id_7491a3_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_archived'], name='teams_team_is_arch_60baa0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('org', 'name')},
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'user'], name='teams_teamm_team_id_49b9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user'], name='teams_teamm_user_id_957e00_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['role'], name='teams_teamm_role_id_c1c81e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
    ]
